"""Create initial tables

Revision ID: af9c5a328261
Revises: 
Create Date: 2025-09-23 09:41:44.291694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af9c5a328261'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('time_bucket', sa.String(length=20), nullable=False),
    sa.Column('bucket_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('model_provider', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('headline_count', sa.Integer(), nullable=True),
    sa.Column('avg_sentiment', sa.Float(), nullable=True),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('sentiment_dispersion', sa.Float(), nullable=True),
    sa.Column('positive_count', sa.Integer(), nullable=True),
    sa.Column('neutral_count', sa.Integer(), nullable=True),
    sa.Column('negative_count', sa.Integer(), nullable=True),
    sa.Column('avg_response_time_ms', sa.Float(), nullable=True),
    sa.Column('cache_hit_rate', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('time_bucket', 'bucket_date', 'ticker', 'company', 'sector', 'industry', 'source', 'model_provider', 'model_name', name='uq_analytics_dimensions')
    )
    op.create_index('idx_analytics_bucket', 'analytics', ['time_bucket', 'bucket_date'], unique=False)
    op.create_index('idx_analytics_sector_bucket', 'analytics', ['sector', 'time_bucket', 'bucket_date'], unique=False)
    op.create_index('idx_analytics_ticker_bucket', 'analytics', ['ticker', 'time_bucket', 'bucket_date'], unique=False)
    op.create_index(op.f('ix_analytics_bucket_date'), 'analytics', ['bucket_date'], unique=False)
    op.create_index(op.f('ix_analytics_industry'), 'analytics', ['industry'], unique=False)
    op.create_index(op.f('ix_analytics_model_name'), 'analytics', ['model_name'], unique=False)
    op.create_index(op.f('ix_analytics_model_provider'), 'analytics', ['model_provider'], unique=False)
    op.create_index(op.f('ix_analytics_sector'), 'analytics', ['sector'], unique=False)
    op.create_index(op.f('ix_analytics_source'), 'analytics', ['source'], unique=False)
    op.create_index(op.f('ix_analytics_ticker'), 'analytics', ['ticker'], unique=False)
    op.create_table('headlines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('normalized_headline', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('is_primary_source', sa.Boolean(), nullable=True),
    sa.Column('headline_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('market_session', sa.String(length=20), nullable=False),
    sa.Column('headline_age_minutes', sa.Integer(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('headline_hash', sa.String(length=64), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('parent_headline_id', sa.String(length=36), nullable=True),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_headline_id'], ['headlines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('headline_hash')
    )
    op.create_index('idx_headline_portfolio_timestamp', 'headlines', ['portfolio_id', 'headline_timestamp'], unique=False)
    op.create_index('idx_headline_sector_industry', 'headlines', ['sector', 'industry'], unique=False)
    op.create_index('idx_headline_ticker_timestamp', 'headlines', ['ticker', 'headline_timestamp'], unique=False)
    op.create_index(op.f('ix_headlines_headline_timestamp'), 'headlines', ['headline_timestamp'], unique=False)
    op.create_index(op.f('ix_headlines_industry'), 'headlines', ['industry'], unique=False)
    op.create_index(op.f('ix_headlines_normalized_headline'), 'headlines', ['normalized_headline'], unique=False)
    op.create_index(op.f('ix_headlines_portfolio_id'), 'headlines', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_headlines_sector'), 'headlines', ['sector'], unique=False)
    op.create_index(op.f('ix_headlines_ticker'), 'headlines', ['ticker'], unique=False)
    op.create_table('portfolio_holdings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('pe', sa.Float(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'ticker', name='uq_portfolio_ticker')
    )
    op.create_index(op.f('ix_portfolio_holdings_exchange'), 'portfolio_holdings', ['exchange'], unique=False)
    op.create_index(op.f('ix_portfolio_holdings_industry'), 'portfolio_holdings', ['industry'], unique=False)
    op.create_index(op.f('ix_portfolio_holdings_portfolio_id'), 'portfolio_holdings', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_holdings_sector'), 'portfolio_holdings', ['sector'], unique=False)
    op.create_index(op.f('ix_portfolio_holdings_ticker'), 'portfolio_holdings', ['ticker'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_log_created', 'system_logs', ['created_at'], unique=False)
    op.create_index('idx_log_level_category', 'system_logs', ['level', 'category'], unique=False)
    op.create_index(op.f('ix_system_logs_category'), 'system_logs', ['category'], unique=False)
    op.create_index(op.f('ix_system_logs_created_at'), 'system_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_index(op.f('ix_system_logs_request_id'), 'system_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_system_logs_user_id'), 'system_logs', ['user_id'], unique=False)
    op.create_table('trading_opportunities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('opportunity_type', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('horizon', sa.String(length=20), nullable=False),
    sa.Column('time_sensitivity', sa.String(length=50), nullable=True),
    sa.Column('expiry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('position_size', sa.Float(), nullable=True),
    sa.Column('risk_reward_ratio', sa.Float(), nullable=True),
    sa.Column('max_risk_amount', sa.Float(), nullable=True),
    sa.Column('volatility_adjusted_size', sa.Float(), nullable=True),
    sa.Column('supporting_headlines', sa.JSON(), nullable=True),
    sa.Column('sentiment_summary', sa.JSON(), nullable=True),
    sa.Column('market_context', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_opportunity_score_priority', 'trading_opportunities', ['score', 'priority'], unique=False)
    op.create_index('idx_opportunity_status_ticker', 'trading_opportunities', ['status', 'ticker'], unique=False)
    op.create_index(op.f('ix_trading_opportunities_priority'), 'trading_opportunities', ['priority'], unique=False)
    op.create_index(op.f('ix_trading_opportunities_score'), 'trading_opportunities', ['score'], unique=False)
    op.create_index(op.f('ix_trading_opportunities_ticker'), 'trading_opportunities', ['ticker'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('finviz_api_key', sa.Text(), nullable=True),
    sa.Column('groq_api_key', sa.Text(), nullable=True),
    sa.Column('openrouter_api_key', sa.Text(), nullable=True),
    sa.Column('finviz_portfolio_numbers', sa.JSON(), nullable=True),
    sa.Column('selected_models', sa.JSON(), nullable=True),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('notification_preferences', sa.JSON(), nullable=True),
    sa.Column('dashboard_layout', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_key_rotation', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('market_data',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('headline_id', sa.String(length=36), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('volume_rel', sa.Float(), nullable=True),
    sa.Column('return_5m', sa.Float(), nullable=True),
    sa.Column('return_30m', sa.Float(), nullable=True),
    sa.Column('return_1d', sa.Float(), nullable=True),
    sa.Column('volatility_5m', sa.Float(), nullable=True),
    sa.Column('volatility_30m', sa.Float(), nullable=True),
    sa.Column('volatility_1d', sa.Float(), nullable=True),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['headline_id'], ['headlines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'timestamp', name='uq_ticker_timestamp')
    )
    op.create_index('idx_market_ticker_timestamp', 'market_data', ['ticker', 'timestamp'], unique=False)
    op.create_index(op.f('ix_market_data_ticker'), 'market_data', ['ticker'], unique=False)
    op.create_index(op.f('ix_market_data_timestamp'), 'market_data', ['timestamp'], unique=False)
    op.create_table('sentiment_aggregates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('headline_id', sa.String(length=36), nullable=False),
    sa.Column('avg_sentiment', sa.Float(), nullable=False),
    sa.Column('avg_confidence', sa.Float(), nullable=False),
    sa.Column('dispersion', sa.Float(), nullable=False),
    sa.Column('majority_vote', sa.Integer(), nullable=False),
    sa.Column('num_models', sa.Integer(), nullable=False),
    sa.Column('model_votes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('avg_confidence >= 0 AND avg_confidence <= 1', name='check_avg_confidence_range'),
    sa.CheckConstraint('avg_sentiment >= -1 AND avg_sentiment <= 1', name='check_avg_sentiment_range'),
    sa.CheckConstraint('majority_vote IN (-1, 0, 1)', name='check_majority_vote_value'),
    sa.ForeignKeyConstraint(['headline_id'], ['headlines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('headline_id')
    )
    op.create_index('idx_aggregate_confidence', 'sentiment_aggregates', ['avg_confidence'], unique=False)
    op.create_index('idx_aggregate_sentiment', 'sentiment_aggregates', ['avg_sentiment'], unique=False)
    op.create_table('sentiment_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('headline_id', sa.String(length=36), nullable=False),
    sa.Column('model_provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('sentiment', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('horizon', sa.String(length=20), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='check_confidence_range'),
    sa.CheckConstraint('sentiment IN (-1, 0, 1)', name='check_sentiment_value'),
    sa.ForeignKeyConstraint(['headline_id'], ['headlines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('headline_id', 'model_provider', 'model_name', name='uq_headline_model')
    )
    op.create_index('idx_sentiment_headline', 'sentiment_analyses', ['headline_id'], unique=False)
    op.create_index('idx_sentiment_model', 'sentiment_analyses', ['model_provider', 'model_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sentiment_model', table_name='sentiment_analyses')
    op.drop_index('idx_sentiment_headline', table_name='sentiment_analyses')
    op.drop_table('sentiment_analyses')
    op.drop_index('idx_aggregate_sentiment', table_name='sentiment_aggregates')
    op.drop_index('idx_aggregate_confidence', table_name='sentiment_aggregates')
    op.drop_table('sentiment_aggregates')
    op.drop_index(op.f('ix_market_data_timestamp'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_ticker'), table_name='market_data')
    op.drop_index('idx_market_ticker_timestamp', table_name='market_data')
    op.drop_table('market_data')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_trading_opportunities_ticker'), table_name='trading_opportunities')
    op.drop_index(op.f('ix_trading_opportunities_score'), table_name='trading_opportunities')
    op.drop_index(op.f('ix_trading_opportunities_priority'), table_name='trading_opportunities')
    op.drop_index('idx_opportunity_status_ticker', table_name='trading_opportunities')
    op.drop_index('idx_opportunity_score_priority', table_name='trading_opportunities')
    op.drop_table('trading_opportunities')
    op.drop_index(op.f('ix_system_logs_user_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_request_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_created_at'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_category'), table_name='system_logs')
    op.drop_index('idx_log_level_category', table_name='system_logs')
    op.drop_index('idx_log_created', table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_portfolio_holdings_ticker'), table_name='portfolio_holdings')
    op.drop_index(op.f('ix_portfolio_holdings_sector'), table_name='portfolio_holdings')
    op.drop_index(op.f('ix_portfolio_holdings_portfolio_id'), table_name='portfolio_holdings')
    op.drop_index(op.f('ix_portfolio_holdings_industry'), table_name='portfolio_holdings')
    op.drop_index(op.f('ix_portfolio_holdings_exchange'), table_name='portfolio_holdings')
    op.drop_table('portfolio_holdings')
    op.drop_index(op.f('ix_headlines_ticker'), table_name='headlines')
    op.drop_index(op.f('ix_headlines_sector'), table_name='headlines')
    op.drop_index(op.f('ix_headlines_portfolio_id'), table_name='headlines')
    op.drop_index(op.f('ix_headlines_normalized_headline'), table_name='headlines')
    op.drop_index(op.f('ix_headlines_industry'), table_name='headlines')
    op.drop_index(op.f('ix_headlines_headline_timestamp'), table_name='headlines')
    op.drop_index('idx_headline_ticker_timestamp', table_name='headlines')
    op.drop_index('idx_headline_sector_industry', table_name='headlines')
    op.drop_index('idx_headline_portfolio_timestamp', table_name='headlines')
    op.drop_table('headlines')
    op.drop_index(op.f('ix_analytics_ticker'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_source'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_sector'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_model_provider'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_model_name'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_industry'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_bucket_date'), table_name='analytics')
    op.drop_index('idx_analytics_ticker_bucket', table_name='analytics')
    op.drop_index('idx_analytics_sector_bucket', table_name='analytics')
    op.drop_index('idx_analytics_bucket', table_name='analytics')
    op.drop_table('analytics')
    # ### end Alembic commands ###
